### ISSUE TITLE
Rasterize wealth index

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnSSTOVE#134]
Create a function to rasterize the relative wealth index inside OnSSTOVE.

**Comment by babakkhavari** [comment]
Code works. But we need to get the resolution to be around 0.022 degrees as discussed in our Slack on the 30th of August. What is the easiest way to do this? Basically we need:
1. ensure the extent is the countries and
2. the resolution is correct

Maybe for this specific case we can modify this:
`    with rasterio.open(raster_base_layer) as src:
        image = features.rasterize(
                    shapes,
                    out_shape=src.shape,
                    transform=src.transform,
                    all_touched=all_touched,
                    fill=nodata)

        out_meta = src.meta

        out_meta.update({"driver": "GTiff",
                         "height": src.height,
                         "width": src.width,
                         "transform": src.transform,
                         'compress': compression,
                         'dtype': dtype,
                         "crs": src.crs,
                         'nodata': nodata})`

**Comment by camiloramirezgo** [comment]
Another option is to sample the data taking the nearest point.
