### ISSUE TITLE
base_fuel calculations if all tech_specs bases are False

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnSSTOVE#187]
This needs to calculate a base_fuel technology, with the weighted average parameters of all technologies.

**Comment by camiloramirezgo** [comment]
This needs to be disaggregated by urban/rural

**Comment by camiloramirezgo** [comment]
We need to move this information from the `Prep_files` to the `Technical_specs`:

Technology | Share | Data type
-- | -- | --
Urb_Cook_Biomass | 0.07089 | float
Urb_Cook_Charcoal | 0.153005 | float
Urb_Cook_Coal | 0 | float
Urb_Cook_Electricity | 0.03696 | float
Urb_Cook_Gas | 0.68971 | float
Urb_Cook_Kerosene | 0.02041 | float
Rur_Cook_Biomass | 0.07089 | float
Rur_Cook_Charcoal | 0.153005 | float
Rur_Cook_Coal | 0 | float
Rur_Cook_Electricity | 0.03696 | float
Rur_Cook_Gas | 0.68971 | float
Rur_Cook_Kerosene | 0.02041 | float

This will make it easier to loop through all technologies and calculate the weighted average of the parameters.

**Comment by camiloramirezgo** [comment]
We would need the following properties from all technologies, which will then be used to calculate eh weighted averages:
```python
['carbon', 'pm25', 'total_time_yr']
```
If the `carbon` or `total_time_yr` have not been calculated fora technology, then the function should call `.carb()` and `.total_time()` for the technology.
