### ISSUE TITLE
Add specifications for Charcoal and Kerosene to tech files

### ISSUE THREAD

**Issue by camiloramirezgo** [Open-Source-Spatial-Clean-Cooking-Tool/OnSSTOVE#202]
The specifications needed are: `energy_content`, `carbon_intensity`, `time_of_cooking`, `efficiency`, `pm25` and `time_of_collection`

**Comment by camiloramirezgo** [comment]
# Kerosene
* `energy_content`: 43 MJ/kg
* `carbon_intensity`: 126 kg/GJ
* `time_of_cooking`: 2.2 or 2.1 h per day
*  `efficiency`: 28%
* `pm25`: 50
* `time_of_collection`: 0

**Comment by babakkhavari** [comment]
Skip Coal, but add Charcoal and Charcoal ICS

**Comment by babakkhavari** [comment]
# Charcoal

**Comment by babakkhavari** [comment]
# Charcoal
* `fuel_cost`:  2 USD/GJ
* `efficiency`:  
* `pm25`: 
* `energy_content`: 30 MJ/kg 
* `carbon_intensity`:  218 kg/GJ
* `time_of_cooking`: 
* `time_of_collection`: 
* `inv_cost`: 
* `tech_life`: 

https://www.pbl.nl/en/publications/towards-universal-access-to-clean-cooking-solutions-in-sub-saharan-africa

**Comment by camiloramirezgo** [comment]
We will use the average values found in SNV page 14

**Comment by babakkhavari** [comment]
# Values to be updated

## Add improved charcoal

## Biogas

- pm25 = 20
- time of cooking = 2 hrs
- inv cost = 497

## Collected improved biomass

- pm25 = 305
- time of cooking = 2.9 hrs
- inv cost = 23

## Collected trad. biomass

- efficiency = 12
- time of cooking = 2.9 hrs
- tech life = 2

## Electricity

- efficiency = 80
- time of cooking = 1.8 
- tech life = 10
- pm25 = 5
- inv cost = 63 

## Kerosene

- efficiency = 35
- time of cooking = 2
- pm25 = 45

## LPG

- efficiency = 50
- time of cooking = 2
- tech life = 10
- inv cost =  52
