### ISSUE TITLE
Proximity function

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnSSTOVE#38]
Function determining the distance from every settlement to different vectors of interst. (raster.py)

**Comment by camiloramirezgo** [comment]
To use the `distance_to_electricity`, one should call as:
First create the model:
```python
nepal = OnSSTOVE(project_crs=3857, cell_size=(1000, 1000))
output_directory = 'test'
nepal.output_directory = output_directory
```
Then add the base layer and reproject it (population)
```python
path = r"data\population_npl_2018-10-01.tif"
os.makedirs('test/rasters/population', exist_ok=True)
population = RasterLayer('rasters', 'population', layer_path=path, resample='sum')
population.reproject(3857, 'test/rasters/population', 1000, 1000)
nepal.base_layer = population
```
Then add a mask layer (admin 0):
```python
path = r"data\npl_admbnda_adm0_nd_20201117.shp"
mask_layer = VectorLayer('vector', 'adm_0', layer_path=path)
os.makedirs('test/vector/adm_0', exist_ok=True)
mask_layer.reproject(3857, 'test/vector/adm_0')
nepal.mask_layer = mask_layer
```
Then add the HV. MV and transformer layers
```python
path = r"data\Distribution coverage - georeferenced.gpkg"
mv_lines = VectorLayer('vector', 'MV_line', layer_path=path)
os.makedirs('test/vector/MV_line', exist_ok=True)
mv_lines.reproject(3857, 'test/vector/MV_line')

path = r"data\HV_lines_georeferenced.shp"
hv_lines = VectorLayer('vector', 'HV_line', layer_path=path)
os.makedirs('test/vector/HV_line', exist_ok=True)
hv_lines.reproject(3857, 'test/vector/HV_line')

path = r"data\trnsformers.shp"
transformers = VectorLayer('vector', 'Transformer', layer_path=path)
os.makedirs('test/vector/Transformer', exist_ok=True)
transformers.reproject(3857, 'test/vector/Transformer')
```
And call the method:
```python
nepal.distance_to_electricity(hv_lines=hv_lines, mv_lines=mv_lines, transformers=transformers)
```
output:
<html>
<body>


geometry | Pop | Night_lights | HV_line_dist | MV_line_dist | Transformer_dist
-- | -- | -- | -- | -- | --
POINT (9065104.530 3518192.836) | 4.137804 | 0.000000 | 49.335587 | 93.776329 | 119.920807
POINT (9095104.530 3510192.836) | 10.798401 | 0.000000 | 27.202942 | 114.201576 | 128.844864
POINT (9046104.530 3507192.836) | 8.405575 | 0.000000 | 36.124783 | 72.111023 | 102.786186
POINT (9108104.530 3500192.836) | 13.607732 | 0.643610 | 12.369317 | 115.260574 | 130.115326
POINT (8975104.530 3490192.836) | 10.356868 | 0.000000 | 23.706539 | 5.830952 | 45.177429


</body>
</html>
