### ISSUE TITLE
Distributing minimum wage

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnSSTOVE#43]
Use the wealth index and minmum wage to generate wealth spatially (do this in onsstove.py)

**Comment by camiloramirezgo** [comment]
We need a method to take the wealth index raster layer as a `RasterLayer` object and the minimum wage value of the country as inputs. Then, in the function we need to define a lower and an upper factor for the minimum wage. I suggest taking 0.2 and 0.5, then the lowest value in the wealth index will get 0.2 * the minimum wage and the highest value 0.5 * the minimum wage.
